customLibraries:
  array:
    - object:
        version: 3.4.0
        language: javascript
        codeString: |
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: uuid
    - object:
        version: 4.17.21
        language: javascript
        codeString: |
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: lodash
    - object:
        version: 2.1.0
        language: javascript
        codeString: |
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: numbro
    - object:
        version: 5.3.2
        language: javascript
        codeString: |
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: papaparse
    - object:
        version: 24.7.2
        language: javascript
        codeString: ''
        libraryName: puppeteer
    - object:
        version: 24.7.2
        language: javascript
        codeString: ''
        libraryName: puppeteer-core
    - object:
        version: 0.5.23
        language: javascript
        codeString: |
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: moment-timezone
    - object:
        version: 3.3.6
        language: javascript
        codeString: ''
        libraryName: puppeteer-extra
name: My First Workflow - Mike Madsen - 2025-05-01 4:03:47 PM
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: |+
          // lodash
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // numbro
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // papaparse
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // moment-timezone
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // uuid
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
          const executablePath = require('puppeteer').executablePath

          const puppeteer = require('puppeteer-extra')

hasProtectedTriggers: false
javascriptLanguageConfiguration:
  object:
    id: 6d9f24b7-b5de-4ff7-be95-16f7e947cfa3
    name: workflow_javascript_fea2ceb6-1553-45d3-bc5a-d15200e48d4d
    description: null
    libraries:
      object:
        uuid:
          object:
            specVersion: 3.4.0
            actualVersion: ''
        lodash:
          object:
            specVersion: 4.17.21
            actualVersion: ''
        numbro:
          object:
            specVersion: 2.1.0
            actualVersion: ''
        papaparse:
          object:
            specVersion: 5.3.2
            actualVersion: ''
        puppeteer:
          object:
            specVersion: 24.7.2
            actualVersion: ''
        puppeteer-core:
          object:
            specVersion: 24.7.2
            actualVersion: ''
        moment-timezone:
          object:
            specVersion: 0.5.23
            actualVersion: ''
        puppeteer-extra:
          object:
            specVersion: 3.3.6
            actualVersion: ''
    librariesFormat: package.json
    language: javascript
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
        examplePathParams: ''
version: 43.0.9
workflowId: fea2ceb6-1553-45d3-bc5a-d15200e48d4d
description: null
workflowTemplate:
  version: 3.219.0
